version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=db-test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 8080:8080
    volumes:
      - ./postgres_data:/var/lib/postgresql/data